[tool.poetry]
name = "wordcab-transcribe"
version = "0.1.0"
description = "ASR FastAPI server using faster-whisper and pyannote-audio."
authors = ["Wordcab <info@wordcab.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
aiohttp = ">=3.8.4"
aiofiles = ">=23.1.0"
cython = ">=0.29.24"
fastapi = ">=0.95.0"
faster-whisper = ">=0.3.0"
ffmpeg-python = ">=0.2.0"
loguru = ">=0.6.0"
nemo-toolkit = { version = ">=1.17.0", extras = ["asr"] }
numpy = "==1.23.1"
pydantic = ">=1.10.7"
python-dotenv = ">=1.0.0"
python-multipart = ">=0.0.6"
scikit-learn = ">=1.2.2"
shortuuid = ">=1.0.0"
torch = ">=1.9,<2.0"
uvicorn = ">=0.21.1"
yt-dlp = ">=2023.3.4"
youtokentome = { git = "https://github.com/gbeckenkamp/YouTokenToMe.git", branch = "add_minimum_requirements" }

[tool.poetry.group.test.dependencies]
black = ">=23.1.0"
coverage = {extras = ["toml"], version = ">=7.2.1"}
darglint = ">=1.8.1"
flake8 = ">=6.0.0"
flake8-bandit = ">=4.1.1"
flake8-bugbear = ">=23.2.13"
flake8-docstrings = ">=1.7.0"
httpx = ">=0.23.3"
isort = ">=5.12.0"
pre-commit = ">=3.2.0"
pre-commit-hooks = ">=4.4.0"
pytest = ">=7.2.2"
pytest-asyncio = ">=0.20.3"
pytest-mock = ">=3.10.0"
pyupgrade = ">=3.3.1"

[tool.isort]
profile = "black"
force_single_line = false
lines_after_imports = 2

[tool.coverage.run]
branch = true
source = ["wordcab_ask", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 50

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
