[tool.poetry]
name = "wordcab-transcribe"
version = "0.4.0"
description = "💬 ASR FastAPI server using faster-whisper and Auto-Tuning Spectral Clustering for diarization."
authors = ["Wordcab <info@wordcab.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.10"
aiohttp = ">=3.8.4"
aiofiles = ">=23.1.0"
argon2-cffi = ">=21.3.0"
ctranslate2 = ">=3.18.0"
fastapi = ">=0.96.0"
faster-whisper = { git = "https://github.com/Wordcab/faster-whisper.git", branch = "master" }
ffmpeg-python = ">=0.2.0"
librosa = ">=0.9.0"
loguru = ">=0.6.0"
nltk = ">=3.6.0"
numpy = "==1.23.1"
onnxruntime = ">=1.15.0"
pandas = ">=1.3.0"
pydantic = ">=1.10.9"
python-dotenv = ">=1.0.0"
python-jose = { extras = ["cryptography"], version = ">=3.3.0" }
python-multipart = ">=0.0.6"
shortuuid = ">=1.0.0"
svix = ">=0.85.1"
torch = "2.0.0"
torchaudio = "2.0.1"
transformers = ">=4.32.1"
uvicorn = ">=0.21.1"
yt-dlp = ">=2023.3.4"
wget = ">=3.2.0"

[tool.poetry.group.test.dependencies]
black = ">=23.1.0"
coverage = { extras = ["toml"], version = ">=7.2.1" }
darglint = ">=1.8.1"
flake8 = ">=6.0.0"
flake8-bandit = ">=4.1.1"
flake8-bugbear = ">=23.2.13"
flake8-docstrings = ">=1.7.0"
httpx = ">=0.23.3"
isort = ">=5.12.0"
pre-commit = ">=3.2.0"
pre-commit-hooks = ">=4.4.0"
pytest = ">=7.2.2"
pytest-asyncio = ">=0.20.3"
pytest-mock = ">=3.10.0"
pyupgrade = ">=3.3.1"

[tool.isort]
profile = "black"
force_single_line = false
lines_after_imports = 2

[tool.coverage.run]
branch = true
source = ["wordcab_transcribe", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 20

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
